Repository navi-dupli/app-movil, pull requests merged in 2022-11, with the labels that each got.

#42 Feature/28
  app/src/main/java/co/navidupli/vinilos/ui/createAlbumScreen/CreateAlbumScreen.kt
Labels: H007

#44 Detalles de funcionamiento
  app/src/main/java/co/navidupli/vinilos/ui/createAlbumScreen/CreateAlbumScreen.kt
Labels: H001

#47 Feature/29
  app/src/androidTest/java/co/navidupli/vinilos/AlbumCreateTest.kt
  app/src/androidTest/java/co/navidupli/vinilos/ExampleInstrumentedTest.kt
  app/src/main/java/co/navidupli/vinilos/bottombar/BottomBar.kt
  app/src/main/java/co/navidupli/vinilos/ui/ProfileScreen/ProfileScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/createAlbumScreen/CreateAlbumScreen.kt
Labels: H007

#52 Finish Release/sprint 1
  .gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  README.md
  app/build.gradle
  app/src/androidTest/java/co/navidupli/vinilos/AlbumCreateTest.kt
  app/src/androidTest/java/co/navidupli/vinilos/AlbumListTest.kt
  app/src/androidTest/java/co/navidupli/vinilos/ComposeRuleExtensions.kt
  app/src/androidTest/java/co/navidupli/vinilos/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/navidupli/vinilos/bottombar/BottomBar.kt
  app/src/main/java/co/navidupli/vinilos/broker/AlbumApiService.kt
  app/src/main/java/co/navidupli/vinilos/broker/RetrofitClient.kt
  app/src/main/java/co/navidupli/vinilos/components/CardComponent.kt
  app/src/main/java/co/navidupli/vinilos/model/Album.kt
  app/src/main/java/co/navidupli/vinilos/model/AlbumCreate.kt
  app/src/main/java/co/navidupli/vinilos/model/AlbumCreated.kt
  app/src/main/java/co/navidupli/vinilos/model/Comment.kt
  app/src/main/java/co/navidupli/vinilos/model/Performer.kt
  app/src/main/java/co/navidupli/vinilos/model/Track.kt
  app/src/main/java/co/navidupli/vinilos/repositories/AlbumRepository.kt
  app/src/main/java/co/navidupli/vinilos/ui/ProfileScreen/ProfileScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/RootScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/albumsScreen/AlbumsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/collectorsScreen/CollectorsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/createAlbumScreen/CreateAlbumScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/theme/Color.kt
  app/src/main/java/co/navidupli/vinilos/ui/theme/Theme.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/CreateAlbumViewModel.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/ListAlbumsViewModel.kt
  app/src/main/res/drawable/image_background_root.png
  app/src/main/res/values/strings.xml
  build.gradle
  result_test/Test Results - All_Tests_API_21.html
  result_test/Test Results - All_Tests_API_29.html
  result_test/Test Results - All_Tests_API_33.html
Labels: H007, H001

#55 Creacion vista modelo detalle album
  app/src/main/java/co/navidupli/vinilos/viewModel/DetailAlbumViewModel.kt
Labels: H002

#56 Consumo servicio detalle album
  app/src/main/java/co/navidupli/vinilos/broker/AlbumApiService.kt
  app/src/main/java/co/navidupli/vinilos/repositories/AlbumRepository.kt
Labels: H002

#57 Crear la interfaz grafica - Detalle de un album
  .idea/misc.xml
  app/src/main/java/co/navidupli/vinilos/broker/AlbumApiService.kt
  app/src/main/java/co/navidupli/vinilos/components/CardComponent.kt
  app/src/main/java/co/navidupli/vinilos/components/DetailComponent.kt
  app/src/main/java/co/navidupli/vinilos/navigation/NavigationHost.kt
  app/src/main/java/co/navidupli/vinilos/navigation/NavigationScreen.kt
  app/src/main/java/co/navidupli/vinilos/repositories/AlbumRepository.kt
  app/src/main/java/co/navidupli/vinilos/ui/albumDetailScreen/AlbumDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/albumsScreen/AlbumsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/theme/Color.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/DetailAlbumViewModel.kt
Labels: H002

#58 Se hace la interfaz grafica de asociar Track
  app/src/main/java/co/navidupli/vinilos/broker/AlbumApiService.kt
  app/src/main/java/co/navidupli/vinilos/repositories/AlbumRepository.kt
  app/src/main/java/co/navidupli/vinilos/ui/associateTracksScreen/AssociateTracksScreen.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/AssociateTracksViewModel.kt
Labels: H008

#60 Feature/19 add view model list performers
  app/src/main/java/co/navidupli/vinilos/model/Collector.kt
  app/src/main/java/co/navidupli/vinilos/model/Performer.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/ListPerformerViewModel.kt
Labels: H003

#62 Creacion interfaz listar artistas
  app/src/main/java/co/navidupli/vinilos/ui/artistsScreen/ArtistsScreen.kt
  app/src/main/res/values/strings.xml
Labels: H003

#63 Se hacen los test HU008
  app/src/androidTest/java/co/navidupli/vinilos/AssociateTrackTest.kt
  app/src/main/java/co/navidupli/vinilos/ui/associateTracksScreen/AssociateTracksScreen.kt
Labels: H008

#65 Se hace los test de la lista de artistas
  app/src/androidTest/java/co/navidupli/vinilos/ArtistListTest.kt
  app/src/main/java/co/navidupli/vinilos/components/CardComponent.kt
  app/src/main/java/co/navidupli/vinilos/components/DetailComponent.kt
  app/src/main/java/co/navidupli/vinilos/ui/albumDetailScreen/AlbumDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/albumsScreen/AlbumsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/artistsScreen/ArtistsScreen.kt
  app/src/main/res/values/strings.xml
Labels: H003

#69 Se hace interfaz grafica de la HU05
  app/src/main/java/co/navidupli/vinilos/components/CardComponent.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/AlbumDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/AlbumsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/ArtistsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/CollectorsScreen.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/ListCollectorsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: H005

#70 Crear VistaModelo
  app/src/main/java/co/navidupli/vinilos/components/CardComponent.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/AlbumDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/AlbumsScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/CollectorsScreen.kt
  app/src/main/java/co/navidupli/vinilos/viewModel/ListCollectorsViewModel.kt
  app/src/main/java/co/navidupli/vinilos/viewmodel/ListAlbumsViewModel.kt
Labels: H005

#71 Feature/23 view model Artist detail
  app/src/main/java/co/navidupli/vinilos/model/Musician.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/ArtistDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/viewmodel/DetailArtistViewModel.kt
Labels: H004

#72 Feature/22 view artist detail
  app/src/main/java/co/navidupli/vinilos/model/Performer.kt
  app/src/main/java/co/navidupli/vinilos/navigation/NavigationHost.kt
  app/src/main/java/co/navidupli/vinilos/navigation/NavigationScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/AlbumDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/ArtistDetailScreen.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/ArtistsScreen.kt
  app/src/main/java/co/navidupli/vinilos/viewmodel/DetailArtistViewModel.kt
Labels: H004

#77 Feature/6 add test list collector
  app/src/androidTest/java/co/navidupli/vinilos/CollectorsListTest.kt
Labels: H005

#79 pruebas detalle coleccionista
  app/src/androidTest/java/co/navidupli/vinilos/CollectorDetailTest.kt
  app/src/main/java/co/navidupli/vinilos/ui/screens/CollectorDetailScreen.kt
Labels: H006

#80 Prueba detalle artista
  app/src/androidTest/java/co/navidupli/vinilos/ArtistDetailTest.kt
Labels: H004
